# Generated by Django 5.0 on 2024-08-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
