# Generated by Django 4.2.6 on 2023-10-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
