# Generated by Django 5.0 on 2024-01-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_img'),
        ),
    ]
