# Generated by Django 5.0 on 2024-01-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/post_img'),
        ),
    ]
